name: metal
channels:
  - anaconda
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - appnope=0.1.4=pyhd8ed1ab_1
  - arch-py=7.2.0=py312he0011b7_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - attrs=24.3.0=py312hca03da5_0
  - beautifulsoup4=4.13.5=py312hca03da5_0
  - blas=1.0=openblas
  - bottleneck=1.4.2=py312ha86b861_0
  - brotli-python=1.0.9=py312h313beb8_8
  - brotlicffi=1.0.9.2=py312h313beb8_1
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.9.9=hca03da5_0
  - certifi=2025.10.5=py312hca03da5_0
  - cffi=1.17.1=py312h3eb5a62_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - colorama=0.4.6=py312hca03da5_0
  - comm=0.2.2=pyhd8ed1ab_1
  - contourpy=1.3.1=py312h48ca7d4_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - debugpy=1.6.7=py312h313beb8_0
  - decorator=5.1.1=pyhd8ed1ab_1
  - et_xmlfile=1.1.0=py312hca03da5_1
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.1.0=pyhd8ed1ab_1
  - expat=2.6.4=h313beb8_0
  - fonttools=4.55.3=py312h80987f9_0
  - freetype=2.12.1=h1192e45_0
  - h11=0.14.0=py312hca03da5_0
  - importlib-metadata=8.5.0=pyha770c72_1
  - ipykernel=6.29.5=pyh57ce528_0
  - ipython=8.31.0=pyh707e725_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jpeg=9e=h80987f9_3
  - jsonschema=4.23.0=py312hca03da5_0
  - jsonschema-specifications=2023.7.1=py312hca03da5_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - kiwisolver=1.4.8=py312h313beb8_0
  - lcms2=2.16=he93ba84_0
  - lerc=4.0.0=h313beb8_0
  - libcxx=14.0.6=h848a8c0_0
  - libdeflate=1.22=h80987f9_0
  - libexpat=2.6.4=h286801f_0
  - libffi=3.4.4=hca03da5_1
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libopenblas=0.3.21=h269037a_0
  - libpng=1.6.39=h80987f9_0
  - libsodium=1.0.18=h27ca646_1
  - libsqlite=3.46.0=hfb93653_0
  - libtiff=4.5.1=hc9ead59_1
  - libwebp-base=1.3.2=h80987f9_1
  - libzlib=1.2.13=hfb2fe0b_6
  - llvm-openmp=14.0.6=hc6e5704_0
  - lz4-c=1.9.4=h313beb8_1
  - matplotlib=3.10.0=py312hca03da5_0
  - matplotlib-base=3.10.0=py312h7ef442a_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - nbformat=5.10.4=py312hca03da5_0
  - ncurses=6.4=h313beb8_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.4.2=py312hca03da5_0
  - numexpr=2.10.1=py312h5d9532f_0
  - numpy=2.0.1=py312h7f4fdc5_1
  - numpy-base=2.0.1=py312he047099_1
  - openjpeg=2.5.2=h54b8e55_0
  - openpyxl=3.1.5=py312h80987f9_0
  - openssl=3.4.0=h39f12f2_0
  - outcome=1.3.0=py312hca03da5_0
  - packaging=24.2=pyhd8ed1ab_2
  - pandas=2.2.3=py312hcf29cfe_0
  - parso=0.8.4=pyhd8ed1ab_1
  - patsy=1.0.1=py312hca03da5_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.1.0=py312h84e58ab_0
  - pip=24.2=py312hca03da5_0
  - platformdirs=4.3.6=pyhd8ed1ab_1
  - plotly=5.24.1=py312h989b03a_1
  - prompt-toolkit=3.0.48=pyha770c72_1
  - psutil=5.9.0=py312h80987f9_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.18.0=pyhd8ed1ab_1
  - pykalman=0.10.2=pyhd8ed1ab_0
  - pyparsing=3.2.0=py312hca03da5_0
  - pysocks=1.7.1=py312hca03da5_0
  - python=3.12.2=hdf0ec26_0_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-fastjsonschema=2.20.0=py312hca03da5_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.12=5_cp312
  - pytz=2024.1=py312hca03da5_0
  - pyzmq=26.2.0=py312h313beb8_0
  - readline=8.2=h1a28f6b_0
  - referencing=0.30.2=py312hca03da5_0
  - requests=2.32.3=py312hca03da5_1
  - rpds-py=0.22.3=py312h2aea54e_0
  - scikit-base=0.12.6=pyhc455866_0
  - scipy=1.15.1=py312ha409365_0
  - seaborn=0.13.2=py312hca03da5_2
  - selenium=4.36.0=pyhcf101f3_0
  - selenium-manager=4.36.0=h8d80559_0
  - setuptools=75.1.0=py312hca03da5_0
  - six=1.17.0=pyhd8ed1ab_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - soupsieve=2.5=py312hca03da5_0
  - sqlite=3.45.3=h80987f9_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.4=py312h80987f9_0
  - tenacity=9.0.0=py312hca03da5_0
  - tk=8.6.14=h6ba3021_0
  - tornado=6.4.2=py312h80987f9_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - trio=0.30.0=py312hca03da5_0
  - trio-websocket=0.12.2=py312hca03da5_0
  - typing-extensions=4.14.1=h4440ef1_0
  - typing_extensions=4.14.1=pyhe01879c_0
  - tzdata=2024b=h04d1e81_0
  - unicodedata2=15.1.0=py312h80987f9_1
  - urllib3=2.5.0=py312hca03da5_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - websocket-client=1.8.0=py312hca03da5_0
  - wheel=0.44.0=py312hca03da5_0
  - wsproto=1.2.0=py312hca03da5_0
  - xz=5.4.6=h80987f9_1
  - zeromq=4.3.5=h313beb8_0
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.2.13=hfb2fe0b_6
  - zstd=1.5.6=hfb09047_0
  - pip:
      - anyio==4.7.0
      - httpcore==0.16.3
      - httpx==0.23.3
      - idna==3.10
      - investiny==0.7.2
      - pydantic==1.10.19
      - rfc3986==1.5.0
      - sniffio==1.3.1
prefix: /Users/michal/miniconda3/envs/metal
